//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collection
    {
        public string C_ID { get; set; }
        public string U_ID { get; set; }
        public string Precision { get; set; }
        public string Details { get; set; }
        public Nullable<double> Depth1 { get; set; }
        public Nullable<double> Depth2 { get; set; }
        public Nullable<int> sort { get; set; }
    }
}
