//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dict
    {
        public string Id { get; set; }
        public string Type { get; set; }
        public string KeyName { get; set; }
        public string ValueName { get; set; }
        public int Sort { get; set; }
        public string Pid { get; set; }
    }
}
