//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fossil
    {
        public string H_ID { get; set; }
        public string C_ID { get; set; }
        public string R_ID { get; set; }
        public string Time { get; set; }
        public string SubTime { get; set; }
        public Nullable<int> Time2 { get; set; }
        public string Authorizer { get; set; }
        public string FossilGroup { get; set; }
        public string TaxonType { get; set; }
        public string CollectFromTreatise { get; set; }
        public Nullable<int> RefDescribingRelation { get; set; }
        public string GenusName { get; set; }
        public string SpeciesName { get; set; }
        public string Position { get; set; }
        public string Length { get; set; }
        public string width { get; set; }
        public string Picture { get; set; }
        public string Notes { get; set; }
    }
}
