//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trias.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TriasEntities : DbContext
    {
        public TriasEntities()
            : base("name=TriasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Dict> Dict { get; set; }
        public DbSet<Reference> Reference { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Rock> Rock { get; set; }
        public DbSet<Unit> Unit { get; set; }
        public DbSet<Formation> Formation { get; set; }
        public DbSet<Section> Section { get; set; }
        public DbSet<Collection> Collection { get; set; }
        public DbSet<Fossil> Fossil { get; set; }
        public DbSet<Geochemical> Geochemical { get; set; }
    }
}
