//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public string S_ID { get; set; }
        public string User_ID { get; set; }
        public string SectionName { get; set; }
        public string RID1 { get; set; }
        public string RID2 { get; set; }
        public string RID3 { get; set; }
        public string Time { get; set; }
        public string SubTime { get; set; }
        public Nullable<int> Time2 { get; set; }
        public Nullable<System.DateTime> EnterTime { get; set; }
        public string Authorizer { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string County { get; set; }
        public string Village { get; set; }
        public Nullable<int> LonDegrees { get; set; }
        public Nullable<int> LonMinutes { get; set; }
        public Nullable<int> LonSeconds { get; set; }
        public Nullable<int> LatDegrees { get; set; }
        public Nullable<int> LatMinutes { get; set; }
        public Nullable<int> LatSeconds { get; set; }
        public string TectonicPlate { get; set; }
        public string Notes { get; set; }
        public string Comments { get; set; }
        public Nullable<double> Altitude { get; set; }
        public Nullable<int> Time2End { get; set; }
        public string TimeEnd { get; set; }
        public string SubTimeEnd { get; set; }
        public Nullable<int> Sthickness { get; set; }
    }
}
