//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Unit
    {
        public string U_ID { get; set; }
        public string F_ID { get; set; }
        public Nullable<double> Thickness { get; set; }
        public string ContactBase { get; set; }
        public string Facies { get; set; }
        public string Environments { get; set; }
        public string Details { get; set; }
    }
}
