//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string User_ID { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public string UserUnit { get; set; }
        public string UserEmail { get; set; }
        public string ResearchField { get; set; }
        public Nullable<bool> isPass { get; set; }
    }
}
