//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trias.Models
{
    using System;
    using System.Collections.Generic;

    public partial class FormationView
    {
        public string F_ID { get; set; }
        public string S_ID { get; set; }
        public string Formation1 { get; set; }
        public string EnvironmentalZones { get; set; }
        public Nullable<double> Thickness { get; set; }
        public string Comments { get; set; }
    }
}
