//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace Trias.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferenceView
    {
        public string R_ID { get; set; }
        public string ReferenceType { get; set; }
        public string FirstAuthor { get; set; }
        public string SecondAuthor { get; set; }
        public string OtherAuthors { get; set; }
        public Nullable<int> Year { get; set; }
        [Required]
        public string Title { get; set; }
        public string BookTitle { get; set; }
        public string Journal { get; set; }
        public string Editor1 { get; set; }
        public string Editor2 { get; set; }
        public string Editor3 { get; set; }
        public string Editor4 { get; set; }
        public string Language { get; set; }
        public string Publisher { get; set; }
        public string Volume { get; set; }
        public string No { get; set; }
        public string PageBegin { get; set; }
        public string PageEnd { get; set; }
        public string DOI { get; set; }
        public string URL1 { get; set; }
        public string URL2 { get; set; }
        public string Comments { get; set; }
    }
}
