//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trias.Models
{
    using System;
    using System.Collections.Generic;

    public partial class RockView
    {
        public string Rock_ID { get; set; }
        public string Type { get; set; }
        public string FU_ID { get; set; }
        public string Color1 { get; set; }
        public string Color2 { get; set; }
        public string Lithology1 { get; set; }
        public string Lithology2 { get; set; }
        public string MainLithology { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Relation { get; set; }
    }
}
